#!/usr/bin/env bash
#a Bash script that displays:
# "To infinity and beyond" indefinitely
# With a sleep 2 in between each iteration
# "I am invincible!!!" when receiving a SIGTERM signa
while :
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
