#!/usr/bin/env bash
# a bash scripts that displays Best School 10 times, and on the 9th iteration Hi
t=0
while ((t <= 10))
do
	if ((t == 9))
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	((t++))
done
