#!/usr/bin/env bash
# a bash script that displays bad luck for the 4th iteration, good luck for the 8th, and Best School for the rest
t=0
while ((t < 10))
do
	if ((t == 3))
	then
		echo "bad luck"
	elif ((t == 7))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((t++))
done
